services:
  - type: web
    name: faselhdx
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: PUBLIC_URL
        value: "https://faselhdx.onrender.com"
      - key: FASELHDX_DOMAIN
        value: "web31912x.faselhdx.best"
